version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx/
    networks:
      - net-php

  php:
    build: ./php/php74/
    volumes:
      - ./www/:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php-fpm/:/var/log/php-fpm
    expose:
      - "9000"
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/my.cnf
      - ./mysql/:/var/lib/mysql/
      - ./log/mysql/:/var/log/mysql/
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    networks:
      - net-redis
    ports:
      - "6379:6379"

networks:
  net-php:
  net-mysql:
  net-redis: